### ISSUE TITLE
Mobile Meta Tag

### ISSUE THREAD

**Issue by Mikeysax** [bountonw/firehose-splurty#2]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by bountonw** [comment]
Yes indeed! Thank you very much. The app is much improved.
`<meta name="viewport" content="width=device-width, initial-scale=1">`
